# Generated by Django 5.1.3 on 2025-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='craftsmanship',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='craftsmanship/'),
        ),
        migrations.AlterField(
            model_name='craftsmanshiplist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='craftsmanship/'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ourteam/'),
        ),
    ]
