# Generated by Django 5.1.3 on 2024-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(default='/', max_length=200, verbose_name='Banner linki'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(default="Bu yerda sizning reklamangiz bo'lishi mumkin edi", verbose_name="Banner haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners_images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Banner nomi'),
        ),
    ]
